# Based on Wolf Paulus's example python-test.yml file and GitHub Actions Python Application template
#
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Assumes all python code is in ./app directory while tests are in ./tests

name: run-tests

env:
  PYTHON_VERSION: "3.13"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    env:
      PYTHONPATH: "./app"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and install virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install -r tests/requirements.txt
          
      - name: Test with pytest
        run: pytest
        env:
          API_KEY: ${{ secrets.API_KEY }}
